# Generated by Django 4.1 on 2022-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0010_answer_file_alter_answer_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
